services:

  mysql:
    image: mysql:8.0
    container_name: waitlist_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    command: start-dev --import-realm
    volumes:
    - ./keycloak/waitlist-realm-export.json:/opt/keycloak/data/import/waitlist-realm-export.json
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: waitlist_keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  backend:
    build: ./backend
    container_name: waitlist_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      KEYCLOAK_BASE_URL: http://keycloak:8080

volumes:
  mysql_data: